---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: {{ .Values.tenant.name }}-release
  namespace: {{ .Values.tenant.namespace }}
spec:
  path: {{ .Values.repository.path }}
  timeout: {{ .Values.repository.release.timeout }}
  interval: {{ .Values.repository.release.interval }}
  serviceAccountName: {{ .Values.tenant.name }}-serviceaccount
  sourceRef:
    name: {{ .Values.tenant.name }}-repository
    namespace: {{ .Values.tenant.namespace }}
    kind: GitRepository
  wait: true
  prune: true
