---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.tenant.name }}-role
  namespace: {{ .Values.tenant.namespace }}
rules:
  # Default base rules
  - apiGroups:
      - ""
    resources:
      - "secrets"
      - "services"
      - "configmaps"
    verbs:
      - get
      - list
      - watch
      - patch
      - create
      - update
      - delete
  # Permissions for managing workloads
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
      - "replicasets"
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  # Permissions for managing network resources
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - "ingresses"
    verbs:
      - get
      - list
      - patch
      - watch
      - create
      - update
      - delete
  # Permissions for managing Flux resources
  - apiGroups:
      - "source.toolkit.fluxcd.io"
    resources:
      - "gitrepositories"
      - "helmrepositories"
    verbs:
      - get
      - list
      - patch
      - watch
      - create
      - update
      - delete
  # Permissions for managing Helm resources
  - apiGroups:
      - "helm.toolkit.fluxcd.io"
    resources:
      - "helmreleases"
    verbs:
      - get
      - list
      - patch
      - watch
      - create
      - update
      - delete
  # Permissions for managing cert-manager resources
  - apiGroups:
      - "cert-manager.io"
    resources:
      - "certificates"
    verbs:
      - get
      - list
      - patch
      - watch
      - create
      - update
      - delete

  {{- if .Values.rbac.additionalRules }}
  # Additional custom rules from values
  {{- toYaml .Values.rbac.additionalRules | nindent 2 }}
  {{- end }}
