---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.tenant.name }}-rolebinding
  namespace: {{ .Values.tenant.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.tenant.name }}-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ .Values.tenant.name }}-serviceaccount
    namespace: {{ .Values.tenant.namespace }}
  - kind: User
    name: gotk:apps:reconciler
